# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Squid-Auth-Plugin-SimpleLDAP
version:      0.01.02
version_from: lib/Net/Squid/Auth/Plugin/SimpleLDAP.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
